# Generated by Django 6.0.4 on 2026-05-15 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_permutas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEvento',
            fields=[
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('historial_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.historial')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('anio_publicado', models.IntegerField()),
                ('editorial', models.CharField(max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('id_libro', models.BigAutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='core.categoria')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='historial',
            name='libro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.libro'),
        ),
        migrations.CreateModel(
            name='SolicitudPermutas',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('libros_ofrecidos', models.ManyToManyField(related_name='solicitud_donde_fue_ofrecido', to='core.libro')),
                ('libros_solicitados', models.ManyToManyField(related_name='solicitudes_donde_fue_solicitado', to='core.libro')),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_recibida', to='core.usuario')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_solicitada', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Permuta',
            fields=[
                ('id_Permuta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_confirmacion', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permuta', to='core.solicitudpermutas')),
            ],
        ),
    ]
