# Generated by Django 6.0.4 on 2026-05-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='dueño',
            new_name='duenio',
        ),
    ]
