# Generated by Django 6.0.4 on 2026-05-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_dueño_libro_duenio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permuta',
            old_name='id_Permuta',
            new_name='id_permuta',
        ),
    ]
