# Generated by Django 6.0.4 on 2026-05-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_permuta_permuta_id_permuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='duenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='core.usuario'),
        ),
    ]
