# Generated by Django 6.0.4 on 2026-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_libro_duenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permuta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
