# Generated by Django 6.0.4 on 2026-05-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitudpermutas_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpermutas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='solicitudpermutas',
            name='fecha_solicitud',
        ),
    ]
